CREATE TABLE `announcements` (
  `announcement_id` CHAR(36) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `summary` VARCHAR(500) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `starts_at` DATETIME NOT NULL,
  `ends_at` DATETIME NULL DEFAULT NULL,
  `venue` VARCHAR(255) NOT NULL,
  `organizer` VARCHAR(255) NULL DEFAULT NULL,
  `audience` VARCHAR(50) NOT NULL DEFAULT 'ALL',
  `status` VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
  `capacity` INT UNSIGNED NULL DEFAULT NULL,
  `registration_link` VARCHAR(255) NULL DEFAULT NULL,
  `contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `contact_email` VARCHAR(255) NULL DEFAULT NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `published_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `updated_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`announcement_id`),
  KEY `announcements_status_starts_at_index` (`status`, `starts_at`),
  KEY `announcements_audience_status_index` (`audience`, `status`),
  KEY `announcements_is_featured_index` (`is_featured`),
  KEY `announcements_created_by_foreign` (`created_by`),
  KEY `announcements_updated_by_foreign` (`updated_by`),
  CONSTRAINT `announcements_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `announcements_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
